[build]
  [context.deploy-preview]
    ignore = "if [[ $HEAD == *feature/* ]]; then exit 1; else exit 0; fi"



//


// database level schema IDs

const level3 = "63202016d019bbf56a0f7892"
const level2 = "63201ff3d019bbf56a0f7890"
const level1 = "631e97abfeacda54e1339958"

 const [levelid, setLevelId] = useState()

 
  const updatelevel = async()=>{
    axios.put(`${url}/levelcreate/${levelid}`,{
      Bonus:bonus,
      Reward:reward,
      NoRefReq:ref
    }).then((res)=>{
      console.log(res)
      notify("Successfull level updated")
    }).catch((e)=>{
      console.log(e)
    })
  }
